package com.hilvano.handsfreedevotion

enum class OldTestament(val bookName: String, val description: String, val value: Int) {
    GENESIS("Genesis", "The book of beginnings", 1),
    EXODUS("Exodus", "The story of Israel's deliverance from Egypt", 2),
    LEVITICUS("Leviticus", "The book of laws and regulations for priests and worship", 3),
    NUMBERS("Numbers", "The census and wilderness wanderings", 4),
    DEUTERONOMY("Deuteronomy", "The second giving of the law", 5),
    JOSHUA("Joshua", "The conquest and division of the Promised Land", 6),
    JUDGES("Judges", "The period of the judges and Israel's cycles of sin", 7),
    RUTH("Ruth", "The story of Ruth and Boaz", 8),
    FIRST_SAMUEL("1 Samuel", "The life of Samuel, Saul, and David", 9),
    SECOND_SAMUEL("2 Samuel", "The reign of King David", 10),
    FIRST_KINGS("1 Kings", "The reigns of King Solomon and other kings", 11),
    SECOND_KINGS("2 Kings", "The fall of Israel and Judah and their kings", 12),
    FIRST_CHRONICLES("1 Chronicles", "A genealogical record of Israel's history", 13),
    SECOND_CHRONICLES("2 Chronicles", "The history of the kings of Judah", 14),
    EZRA("Ezra", "The return from exile and rebuilding of the temple", 15),
    NEHEMIAH("Nehemiah", "The rebuilding of Jerusalem's walls", 16),
    ESTHER("Esther", "The story of Esther and how she saved her people", 17),
    JOB("Job", "The suffering and restoration of Job", 18),
    PSALMS("Psalms", "A collection of songs and prayers", 19),
    PROVERBS("Proverbs", "Wisdom sayings and practical advice", 20),
    ECCLESIASTES("Ecclesiastes", "Reflections on the meaning of life", 21),
    SONG_OF_SOLOMON("Song of Solomon", "A poetic love song", 22),
    ISAIAH("Isaiah", "Prophecies of judgment and hope", 23),
    JEREMIAH("Jeremiah", "The prophecies and warnings of Jeremiah", 24),
    LAMENTATIONS("Lamentations", "Poetic expressions of grief for Jerusalem", 25),
    EZEKIEL("Ezekiel", "Visions, prophecies, and symbolic actions", 26),
    DANIEL("Daniel", "The story of Daniel and apocalyptic visions", 27),
    HOSEA("Hosea", "Hosea's marriage and prophecies to Israel", 28),
    JOEL("Joel", "The prophecy of Joel and the day of the Lord", 29),
    AMOS("Amos", "The prophecies and visions of Amos", 30),
    OBADIAH("Obadiah", "The prophecy against Edom", 31),
    JONAH("Jonah", "Jonah's mission and the repentance of Nineveh", 32),
    MICAH("Micah", "The prophecies and judgments of Micah", 33),
    NAHUM("Nahum", "The prophecy of Nahum against Nineveh", 34),
    HABAKKUK("Habakkuk", "Habakkuk's questions and God's answers", 35),
    ZEPHANIAH("Zephaniah", "The prophecies of Zephaniah", 36),
    HAGGAI("Haggai", "Haggai's call to rebuild the temple", 37),
    ZECHARIAH("Zechariah", "Visions and prophecies of Zechariah", 38),
    MALACHI("Malachi", "The prophecies of Malachi", 39)
}